"""create shift_requests table

Revision ID: ac3ca7ded235
Revises: 40f483e18342
Create Date: 2026-07-08 13:40:30.277708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac3ca7ded235'
down_revision: Union[str, Sequence[str], None] = '40f483e18342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('shift_type_id', sa.Integer(), nullable=True),
    sa.Column('request_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shift_type_id'], ['shift_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_requests_user_id'), 'shift_requests', ['user_id'], unique=False)
    op.create_index(op.f('ix_shift_requests_work_date'), 'shift_requests', ['work_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shift_requests_work_date'), table_name='shift_requests')
    op.drop_index(op.f('ix_shift_requests_user_id'), table_name='shift_requests')
    op.drop_table('shift_requests')
    # ### end Alembic commands ###
